In [2]:
pip install xlrd

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xlrd in C:\Users\jbaut\AppData\Roaming\Python\Python313\site-packages (2.0.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

df = pd.read_excel("GSAF5.xls")
df.shape

(7125, 23)

In [5]:
df.head(3)

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,18th September,2026.0,Unprovoked,Australia,Western Australia,Sorrento Beach Perth,Swimming,Greg O'Neil,M,63,...,Great White Shark 6m (20ft),Keith Cowley: Kevin McMurray Trackingsharks.co...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16th September,2026.0,Unprovoked,Canada,Quebec,Off the coast of Perce Le Bilbo dive site,Diving,Unknown Male,M,?,...,Great White Shark,Keith Cowley: Kevin McMurray Trackingsharks.co...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,14th September,2026.0,Unprovoked,Bahamas,Bimini,Bimini Island,Swimming,Unknown Austrian Tourist,F,37,...,Unknown,Kevin McMurray Trackingsharks.com: Keith Cowley,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_sex_age.isna().sum()

Sex     578
Age    2994
dtype: int64

Se realiza una comprobación de los valores nulos en cada columna

In [8]:
df_sex_age["Sex"].value_counts(dropna=False)

Sex
M        5709
F         818
NaN       578
M           8
?           2
F           2
N           2
M F         1
 M          1
m           1
lli         1
M x 2       1
.           1
Name: count, dtype: int64

Se detecta los valores escritos de distintas maneras, espacios, errores.

In [57]:
df_sex_age["Sex"] = df_sex_age["Sex"].str.strip().str.upper()
df_sex_age["Sex"] = df_sex_age["Sex"].replace({
    "N":"M",
    "M F":"M",
    "M X 2 ":"M",
    "?":"Unknown",
    "LLI":"Unknown",
    ".": "Unknown"
}).fillna("Unknwn")
df_sex_age["Sex"].value_counts(dropna=False)

Sex
M          5723
F           820
UNKNOWN     582
Name: count, dtype: int64

Se realiza correccion.
"En el caso de M X 2,se realizo una comprobación previa donde se comprobo que se anotaron dos nombres en el mismo expediente,se procedio a averiguar si se habia creado un expediente para ambas personas,posteriomente se comprobo que se habia anotado por error dos nombres en un mismo expediente, cuando cada uno tenia creado el suyo.
Tambien nos percatamos de que habian dos expedientes con el mismo nombre, se reviso los expedientes y se trataba de dos incidentes de la misma persona en lugares y fechas diferentes.
Despues de esta comprobación se aprovecho la formula de correccion y se añadio el dato de M X 2.

In [33]:
filtro = df["Name"].isin(["Jhon Lippoth", "Mark Adams"])
df.loc[filtro,["Name", "Sex", "Age"]]

              Name Sex  Age
1332    Mark Adams   M   42
3759  Jhon Lippoth   M  NaN
7126    Mark Adams   M  NaN

In [32]:
df.loc[[1332, 3759, 7126]]

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
1332,25-Jun-2014,2014.0,Unprovoked,BAHAMAS,Abaco Islands,NaN,Spearfishing,Mark Adams,M,42,...,"Caribbean reef shark, 7' to 8'","A. Brenneka, Shark Attack Survivors, M. Adams",2014.06.25-Adams.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.06.25,2014.06.25,5789.0,NaN,NaN
3759,23-Oct-1962,1982.0,Sea Disaster,USA,Carolina coast,NaN,Yacht Trashman capsized in storm,Jhon Lippoth,M,NaN,...,NaN,"New York Times, 10/31/1982",1982.10.00-Trashman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1982.10.23,1982.10.23,3362.0,NaN,NaN
7126,23-Oct-1962,1982.0,Sea Disaster,USA,Carolina coast,NaN,Yacht Trashman capsized in storm,Mark Adams,M,NaN,...,NaN,"New York Times, 10/31/1982",1982.10.00-Trashman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1982.10.23,1982.10.23,3362.0,NaN,NaN

In [49]:
percentages = df_sex_age["Sex"].value_counts(normalize=True).loc[["M", "F"]]
percentages = percentages / percentages.sum() * 100
percentages.round(2)

Sex
M    87.47
F    12.53
Name: proportion, dtype: float64

Se calcula el porcentaje de accidentes registrados por sexo, considerando únicamente hombres y mujeres.Observamos que el 87,47% corresponde a hombres y el 12,53%  a mujeres.

In [54]:
df_sex_age["Age"] = pd.to_numeric(df_sex_age["Age"], errors="coerce")
df_sex_age.groupby("Sex")["Age"].mean().loc[["M", "F"]].round(0).astype(int)

Sex
M    28
F    28
Name: Age, dtype: int64

Calculamos la edad media de las personas registradas en accidentes, separando hombres y mujeres.El resultado fue de 28 años en ambos grupos.
CONCLUSION:La mayoria de los accidentes registrados corresponden a hombres y la edad media de ambos sexos es de 28 años.